### ISSUE TITLE
Supplier EVN expected readings

### ISSUE THREAD

**Issue by boredomwontgetus** [tirolerstefan/kaifa#10]
Hi!

I am not sure this is me expecting too much or if this is just state of the art.
I have your awesome script running against my Smartmeter provided by EVN.
It works wonderful so far. Thank you very much for the effort. 

The only thing i am a bit wondering about is the amount of information i get out of it. 
The only two readings i get are values for `1.8.0` and `2.8.0`. 

Am i wrong thinking that with a SmartMeter i should be able to read more data from the device? 

Thank you in advance, Tom!

**Comment by tirolerstefan** [comment]
Hi Tom! 

The easy answer is - I don't need more than those two values.
Currently, this script is only supporting the SolarView Export format which requires 1.8.0 and 2.8.0.
But it should be no problem writing other values to any file on disk if requested.

Bye,
Stefan

**Comment by boredomwontgetus** [comment]
Hey Stefan!

Thank you very much. I understand. I will try to implement it myself but will fork and work on MQTT first. 
I'll let you know if i hit my boundaries :)

**Comment by tirolerstefan** [comment]
If you have a tested draft, I'm really looking forward to a pull request!
