### ISSUE TITLE
keine Daten

### ISSUE THREAD

**Issue by fritzi1302** [tirolerstefan/kaifa#24]
Hallo Stefan ich bekomme beim debug log incomplete segment: b zurück habe den port auf ttyAMA0 der heißt bei mir so kannst du mir weiterhelfen danke

**Comment by Markus-Bader** [comment]
Hi @fritzi1302 

Wie hast du das Problem damals lösen können? Stehe aktuell vor dem gleichen Problem.

Danke und LG

**Comment by fritzi1302** [comment]
Hi Markus,

Ich habe es leider aufgegeben
Lg
