### ISSUE TITLE
Exportfunktion Homematic und/oder iobroker

### ISSUE THREAD

**Issue by Dax88** [tirolerstefan/kaifa#7]
Wäre es möglich eine Export-Funktion für Homematic oder ioBroker einzubauen?

**Comment by tirolerstefan** [comment]
How should this export look like?

**Comment by boredomwontgetus** [comment]
May i kindly suggest a more open/generic export implementation like MQTT?

**Comment by Dax88** [comment]
MQTT sounds great!

**Comment by tirolerstefan** [comment]
Feel free to give an example or add an example implementation as pull request for a better overview.

**Comment by boredomwontgetus** [comment]
yeah, once i get my meter i will give it a shot and file a PR.

**Comment by tirolerstefan** [comment]
this will be done in issue #9 / #12

**Comment by tirolerstefan** [comment]
Duplicate of #9
